site_name: 学习笔记
site_url: https://github.com/mrasea
site_author: mrasea
site_description: 个人学习笔记

repo_url: https://github.com/mrasea/leaning
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024-2024 mrasea</br>The website content is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>


theme:
  name: material
  language: zh
  features:
    - content.code.copy
    - content.action.edit
    # - content.action.view
    - navigation.top
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
nav:
  - 介绍: index.md
  - hello glgo 学习:
    - hello_algo/index.md
    - hello_algo/install.md
  - MkDocs 学习:
    - mkdocs/index.md
    - mkdocs/material.md
  - 工具使用:
    - tool/git.md
    - tool/rust.md